[package]
name = "slack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.11", features = ["json"]}
tokio = { version = "1", features = ["full"]}
scraper = "0.16.0"
axum = "0.6.18"
serde = "1.0"
serde_json = "1.0.96"
derive-new = "0.5.9"
tower-http = { version = "0.4.0", features = ["cors"] }


